export const COUNTRY_DATA: Record<string, { name: string; currency: string; symbol: string; timezone: string; emergency: string; code: string }> = {
  "AR": {"code": "AR", "name": "Argentina", "currency": "ARS", "symbol": "$", "timezone": "America/Argentina/Buenos_Aires", "emergency": "911"},
  "AU": {"code": "AU", "name": "Australia", "currency": "AUD", "symbol": "$", "timezone": "Australia/Sydney", "emergency": "000"},
  "AT": {"code": "AT", "name": "Austria", "currency": "EUR", "symbol": "€", "timezone": "Europe/Vienna", "emergency": "112"},
  "BE": {"code": "BE", "name": "Belgium", "currency": "EUR", "symbol": "€", "timezone": "Europe/Brussels", "emergency": "112"},
  "BR": {"code": "BR", "name": "Brazil", "currency": "BRL", "symbol": "R$", "timezone": "America/Sao_Paulo", "emergency": "190"},
  "CA": {"code": "CA", "name": "Canada", "currency": "CAD", "symbol": "$", "timezone": "America/Toronto", "emergency": "911"},
  "CL": {"code": "CL", "name": "Chile", "currency": "CLP", "symbol": "$", "timezone": "America/Santiago", "emergency": "133"},
  "CN": {"code": "CN", "name": "China", "currency": "CNY", "symbol": "¥", "timezone": "Asia/Shanghai", "emergency": "110"},
  "CO": {"code": "CO", "name": "Colombia", "currency": "COP", "symbol": "$", "timezone": "America/Bogota", "emergency": "123"},
  "DK": {"code": "DK", "name": "Denmark", "currency": "DKK", "symbol": "kr", "timezone": "Europe/Copenhagen", "emergency": "112"},
  "EG": {"code": "EG", "name": "Egypt", "currency": "EGP", "symbol": "E£", "timezone": "Africa/Cairo", "emergency": "122"},
  "FI": {"code": "FI", "name": "Finland", "currency": "EUR", "symbol": "€", "timezone": "Europe/Helsinki", "emergency": "112"},
  "FR": {"code": "FR", "name": "France", "currency": "EUR", "symbol": "€", "timezone": "Europe/Paris", "emergency": "112"},
  "DE": {"code": "DE", "name": "Germany", "currency": "EUR", "symbol": "€", "timezone": "Europe/Berlin", "emergency": "112"},
  "HK": {"code": "HK", "name": "Hong Kong", "currency": "HKD", "symbol": "$", "timezone": "Asia/Hong_Kong", "emergency": "999"},
  "IN": {"code": "IN", "name": "India", "currency": "INR", "symbol": "₹", "timezone": "Asia/Kolkata", "emergency": "112"},
  "ID": {"code": "ID", "name": "Indonesia", "currency": "IDR", "symbol": "Rp", "timezone": "Asia/Jakarta", "emergency": "112"},
  "IE": {"code": "IE", "name": "Ireland", "currency": "EUR", "symbol": "€", "timezone": "Europe/Dublin", "emergency": "112"},
  "IL": {"code": "IL", "name": "Israel", "currency": "ILS", "symbol": "₪", "timezone": "Asia/Jerusalem", "emergency": "100"},
  "IT": {"code": "IT", "name": "Italy", "currency": "EUR", "symbol": "€", "timezone": "Europe/Rome", "emergency": "112"},
  "JP": {"code": "JP", "name": "Japan", "currency": "JPY", "symbol": "¥", "timezone": "Asia/Tokyo", "emergency": "110"},
  "KE": {"code": "KE", "name": "Kenya", "currency": "KES", "symbol": "KSh", "timezone": "Africa/Nairobi", "emergency": "999"},
  "MY": {"code": "MY", "name": "Malaysia", "currency": "MYR", "symbol": "RM", "timezone": "Asia/Kuala_Lumpur", "emergency": "999"},
  "MX": {"code": "MX", "name": "Mexico", "currency": "MXN", "symbol": "$", "timezone": "America/Mexico_City", "emergency": "911"},
  "NL": {"code": "NL", "name": "Netherlands", "currency": "EUR", "symbol": "€", "timezone": "Europe/Amsterdam", "emergency": "112"},
  "NZ": {"code": "NZ", "name": "New Zealand", "currency": "NZD", "symbol": "$", "timezone": "Pacific/Auckland", "emergency": "111"},
  "NG": {"code": "NG", "name": "Nigeria", "currency": "NGN", "symbol": "₦", "timezone": "Africa/Lagos", "emergency": "112"},
  "NO": {"code": "NO", "name": "Norway", "currency": "NOK", "symbol": "kr", "timezone": "Europe/Oslo", "emergency": "112"},
  "PE": {"code": "PE", "name": "Peru", "currency": "PEN", "symbol": "S/", "timezone": "America/Lima", "emergency": "105"},
  "PH": {"code": "PH", "name": "Philippines", "currency": "PHP", "symbol": "₱", "timezone": "Asia/Manila", "emergency": "911"},
  "RU": {"code": "RU", "name": "Russia", "currency": "RUB", "symbol": "₽", "timezone": "Europe/Moscow", "emergency": "112"},
  "SA": {"code": "SA", "name": "Saudi Arabia", "currency": "SAR", "symbol": "ر.س", "timezone": "Asia/Riyadh", "emergency": "999"},
  "SG": {"code": "SG", "name": "Singapore", "currency": "SGD", "symbol": "$", "timezone": "Asia/Singapore", "emergency": "999"},
  "ZA": {"code": "ZA", "name": "South Africa", "currency": "ZAR", "symbol": "R", "timezone": "Africa/Johannesburg", "emergency": "10111"},
  "KR": {"code": "KR", "name": "South Korea", "currency": "KRW", "symbol": "₩", "timezone": "Asia/Seoul", "emergency": "112"},
  "ES": {"code": "ES", "name": "Spain", "currency": "EUR", "symbol": "€", "timezone": "Europe/Madrid", "emergency": "112"},
  "LK": {"code": "LK", "name": "Sri Lanka", "currency": "LKR", "symbol": "Rs", "timezone": "Asia/Colombo", "emergency": "119"},
  "SE": {"code": "SE", "name": "Sweden", "currency": "SEK", "symbol": "kr", "timezone": "Europe/Stockholm", "emergency": "112"},
  "CH": {"code": "CH", "name": "Switzerland", "currency": "CHF", "symbol": "CHF", "timezone": "Europe/Zurich", "emergency": "112"},
  "TW": {"code": "TW", "name": "Taiwan", "currency": "TWD", "symbol": "NT$", "timezone": "Asia/Taipei", "emergency": "110"},
  "TH": {"code": "TH", "name": "Thailand", "currency": "THB", "symbol": "฿", "timezone": "Asia/Bangkok", "emergency": "191"},
  "TR": {"code": "TR", "name": "Turkey", "currency": "TRY", "symbol": "₺", "timezone": "Europe/Istanbul", "emergency": "112"},
  "AE": {"code": "AE", "name": "United Arab Emirates", "currency": "AED", "symbol": "د.إ", "timezone": "Asia/Dubai", "emergency": "999"},
  "GB": {"code": "GB", "name": "United Kingdom", "currency": "GBP", "symbol": "£", "timezone": "Europe/London", "emergency": "999"},
  "US": {"code": "US", "name": "United States", "currency": "USD", "symbol": "$", "timezone": "America/New_York", "emergency": "911"},
  "VN": {"code": "VN", "name": "Vietnam", "currency": "VND", "symbol": "₫", "timezone": "Asia/Ho_Chi_Minh", "emergency": "113"}
};
